services:
  backend:
    build: ./dienthoai-shop
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      # Thay đổi 'db' thành 'host.docker.internal' để trỏ tới máy chủ của bạn
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://host.docker.internal:1433;databaseName=dienthoai_shop_db;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa" # Thay bằng username của bạn
      SPRING_DATASOURCE_PASSWORD: "Tuan2972005." # Thay bằng password của bạn
    # Không còn 'depends_on: db'
    networks:
      - monitoring-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./dienthoai-shop-frontend
    container_name: frontend-app
    ports:
      # Cổng 5173 là cổng mặc định của Vite dev server. Nếu bạn build ra file tĩnh
      # và phục vụ bằng Nginx trong Docker, port bên trong container sẽ là 80.
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-storage: {}
