services:
  backend:
    build: ./dienthoai-shop
    # Tên image này đã được định nghĩa rõ ràng, rất tốt!
    image: duongtuan05/dienthoai-shop-backend:${TAG:-latest}
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://host.docker.internal:1433;databaseName=dienthoai_shop_db;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "Tuan2972005."
    networks:
      - monitoring-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./dienthoai-shop-frontend
    image: duongtuan05/dienthoai-shop-frontend:${TAG:-latest}
    container_name: frontend-app
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  grafana-storage: {}
