version: "3.8"

networks:
  monitoring-net:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "tuan2972005"
    ports:
      - "1433:1433"
    networks:
      - monitoring-net
    restart: unless-stopped

  backend:
    build: ./dienthoai-shop
    image: duongtuan05/dienthoai-shop-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://db:1433;databaseName=dienthoai_shop_db;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "tuan2972005"
    depends_on:
      - db
    networks:
      - monitoring-net
    restart: unless-stopped

  frontend:
    build: ./dienthoai-shop-frontend
    image: duongtuan05/dienthoai-shop-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - monitoring-net
    restart: unless-stopped

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - monitoring-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net
    restart: unless-stopped
