version: "3.8"

networks:
  monitoring-net:

services:
  backend:
    build: ./dienthoai-shop
    container_name: backend_app
    image: duongtuan05/dienthoai-shop-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://host.docker.internal:1433;databaseName=dienthoai_shop_db;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "Tuan2972005."
    networks:
      - monitoring-net

  frontend:
    build: ./dienthoai-shop-frontend
    container_name: frontend_app
    image: duongtuan05/dienthoai-shop-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net
