version: "3.8"

networks:
  monitoring-net:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Tuan2972005."
    ports:
      - "1433:1433"
    networks:
      - monitoring-net

  backend:
    build: ./dienthoai-shop
    container_name: backend_app
    image: duongtuan05/dienthoai-shop-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://db:1433;databaseName=dienthoai_shop_db;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "Tuan2972005."
    depends_on:
      - db
    networks:
      - monitoring-net

  frontend:
    build: ./dienthoai-shop-frontend
    container_name: frontend_app
    image: duongtuan05/dienthoai-shop-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest # <-- Quay lại dùng image gốc
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # <-- Sử dụng volume
    depends_on:
      - backend
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net
